app:
  build: .
  container_name: umpire-auditor
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/umpire-auditor
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
postgres:
  image: postgres:9.4
  volumes:
    - ./db/dumps:/app-db-dumps
  ports:
    - "5432"
redis:
  image: redis:3.0.7-alpine
  ports:
    - "6379"

